import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Algeria becomes a region of its own, and a region can be highlighted.
 *
 * Schema only: the `algeria` enum value on both origin_region columns and on
 * regions.slug, plus `regions.highlighted`. All additive, so it can go in
 * before the deploy that reads it.
 *
 * The rows that use the new value are in the next migration. Postgres refuses
 * a freshly added enum value inside the transaction that added it, and each
 * migration runs in its own transaction.
 *
 * Generated by `payload migrate:create` against the banner-product snapshot.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_products_origin_region" ADD VALUE 'algeria';
  ALTER TYPE "public"."enum__products_v_version_origin_region" ADD VALUE 'algeria';
  ALTER TYPE "public"."enum_regions_slug" ADD VALUE 'algeria' BEFORE 'europe';
  ALTER TABLE "regions" ADD COLUMN "highlighted" boolean DEFAULT false;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "products" ALTER COLUMN "origin_region" SET DATA TYPE text;
  DROP TYPE "public"."enum_products_origin_region";
  CREATE TYPE "public"."enum_products_origin_region" AS ENUM('europe', 'middle-east', 'africa', 'latin-america', 'north-america', 'asia', 'oceania');
  ALTER TABLE "products" ALTER COLUMN "origin_region" SET DATA TYPE "public"."enum_products_origin_region" USING "origin_region"::"public"."enum_products_origin_region";
  ALTER TABLE "_products_v" ALTER COLUMN "version_origin_region" SET DATA TYPE text;
  DROP TYPE "public"."enum__products_v_version_origin_region";
  CREATE TYPE "public"."enum__products_v_version_origin_region" AS ENUM('europe', 'middle-east', 'africa', 'latin-america', 'north-america', 'asia', 'oceania');
  ALTER TABLE "_products_v" ALTER COLUMN "version_origin_region" SET DATA TYPE "public"."enum__products_v_version_origin_region" USING "version_origin_region"::"public"."enum__products_v_version_origin_region";
  ALTER TABLE "regions" ALTER COLUMN "slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_regions_slug";
  CREATE TYPE "public"."enum_regions_slug" AS ENUM('europe', 'middle-east', 'africa', 'latin-america', 'north-america', 'asia', 'oceania');
  ALTER TABLE "regions" ALTER COLUMN "slug" SET DATA TYPE "public"."enum_regions_slug" USING "slug"::"public"."enum_regions_slug";
  ALTER TABLE "regions" DROP COLUMN "highlighted";`)
}
