import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Banners can feature a catalogue product (`banners.product`).
 *
 * Purely additive: one nullable column, its foreign key and index. Code that
 * predates the field never selects the column, so this can be applied before
 * the deploy that reads it — and must be, because that deploy's banner query
 * selects `product_id`.
 *
 * Generated by `payload migrate:create` against the partner-portal snapshot;
 * the delta came out exactly as expected, so the snapshot is trustworthy now.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "banners" ADD COLUMN "product_id" integer;
  ALTER TABLE "banners" ADD CONSTRAINT "banners_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "banners_product_idx" ON "banners" USING btree ("product_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "banners" DROP CONSTRAINT "banners_product_id_products_id_fk";
  
  DROP INDEX "banners_product_idx";
  ALTER TABLE "banners" DROP COLUMN "product_id";`)
}
