/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    orders: Order;
    'b2b-inquiries': B2BInquiry;
    products: Product;
    categories: Category;
    brands: Brand;
    regions: Region;
    suppliers: Supplier;
    warehouses: Warehouse;
    'vendor-applications': VendorApplication;
    'chef-profiles': ChefProfile;
    pages: Page;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    recipes: Recipe;
    testimonials: Testimonial;
    banners: Banner;
    media: Media;
    users: User;
    'newsletter-subscribers': NewsletterSubscriber;
    team: Team;
    'office-locations': OfficeLocation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'b2b-inquiries': B2BInquiriesSelect<false> | B2BInquiriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    'vendor-applications': VendorApplicationsSelect<false> | VendorApplicationsSelect<true>;
    'chef-profiles': ChefProfilesSelect<false> | ChefProfilesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'office-locations': OfficeLocationsSelect<false> | OfficeLocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  /**
   * Set by the Stripe webhook — not by the checkout redirect.
   */
  paymentStatus: 'unpaid' | 'paid' | 'failed' | 'refunded' | 'invoice';
  type?: ('retail' | 'b2b') | null;
  currency: 'USD' | 'AED' | 'GBP' | 'EUR' | 'INR';
  /**
   * The note the customer left at checkout. Read-only — these are their words.
   */
  notes?: string | null;
  /**
   * Staff-only. Never shown to the customer.
   */
  internalNotes?: string | null;
  fulfillment?: {
    carrier?: ('dhl' | 'fedex' | 'ups' | 'aramex' | 'emirates-post' | 'local-courier' | 'pickup' | 'other') | null;
    /**
     * Adding one is recorded on the Activity tab.
     */
    trackingNumber?: string | null;
    /**
     * Stamped automatically when the status becomes Shipped.
     */
    shippedAt?: string | null;
    /**
     * Stamped automatically when the status becomes Delivered.
     */
    deliveredAt?: string | null;
  };
  shippingAddress?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Raw audit rows. Rendered above.
   */
  timeline?:
    | {
        event?: string | null;
        note?: string | null;
        at?: string | null;
        by?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  orderNumber: string;
  user?: (number | null) | User;
  /**
   * Populated for guest checkouts.
   */
  guestEmail?: string | null;
  /**
   * Line items snapshot what was bought. They must stay readable after the catalogue is re-imported, so the product relationship is a convenience — the snapshot fields are the record.
   */
  items: {
    /**
     * Null once the product is removed from the catalogue.
     */
    product?: (number | null) | Product;
    /**
     * The exact variant bought. This is the durable identifier.
     */
    variantSku?: string | null;
    /**
     * Product title as it was at purchase.
     */
    titleSnapshot?: string | null;
    /**
     * Variant size as it was at purchase, e.g. "125g".
     */
    sizeSnapshot?: string | null;
    quantity: number;
    unitAmount: number;
    currency: string;
    id?: string | null;
  }[];
  totals: {
    subtotal: number;
    shipping?: number | null;
    tax?: number | null;
    total: number;
  };
  /**
   * Stripe Checkout session that was opened for this order.
   */
  stripeCheckoutSessionId?: string | null;
  /**
   * Stripe payment intent ID for this order.
   */
  stripePaymentIntentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  phone?: string | null;
  /**
   * Admin sees and edits everything. Order fulfilment can sign in and move orders along — status, carrier, tracking, internal notes — and nothing else. Customer is storefront-only and cannot open this panel. Chef and Vendor are partner-portal roles: also storefront-only, but they unlock /portal — a chef authors recipes, a vendor follows its own application.
   */
  roles: ('admin' | 'fulfilment' | 'customer' | 'chef' | 'vendor')[];
  addresses?:
    | {
        /**
         * e.g. "Home", "Office"
         */
        label?: string | null;
        line1: string;
        line2?: string | null;
        city: string;
        state?: string | null;
        postalCode: string;
        country: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  preferredCurrency?: ('USD' | 'AED' | 'GBP' | 'EUR' | 'INR') | null;
  preferredLanguage?: ('en' | 'ar' | 'es' | 'fr') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Derived from the title on save.
   */
  slug: string;
  /**
   * Product-level identifier. Each variant carries its own SKU too.
   */
  sku: string;
  /**
   * Must be a leaf category, not a department.
   */
  category: number | Category;
  brand?: (number | null) | Brand;
  supplier?: (number | null) | Supplier;
  origin: {
    /**
     * Country of origin. Drives the region filter.
     */
    country:
      | 'DZ'
      | 'AR'
      | 'AU'
      | 'AT'
      | 'BH'
      | 'BD'
      | 'BE'
      | 'BO'
      | 'BR'
      | 'KH'
      | 'CA'
      | 'CL'
      | 'CN'
      | 'CO'
      | 'CR'
      | 'CI'
      | 'HR'
      | 'CU'
      | 'CY'
      | 'CZ'
      | 'DK'
      | 'DO'
      | 'EC'
      | 'EG'
      | 'SV'
      | 'ET'
      | 'FI'
      | 'FR'
      | 'DE'
      | 'GH'
      | 'GR'
      | 'GT'
      | 'HN'
      | 'HU'
      | 'IN'
      | 'ID'
      | 'IR'
      | 'IQ'
      | 'IE'
      | 'IL'
      | 'IT'
      | 'JP'
      | 'JO'
      | 'KE'
      | 'KW'
      | 'LB'
      | 'LY'
      | 'MG'
      | 'MY'
      | 'MX'
      | 'MA'
      | 'NP'
      | 'NL'
      | 'NZ'
      | 'NI'
      | 'NG'
      | 'NO'
      | 'OM'
      | 'PK'
      | 'PS'
      | 'PA'
      | 'PY'
      | 'PE'
      | 'PH'
      | 'PL'
      | 'PT'
      | 'QA'
      | 'RO'
      | 'RW'
      | 'SA'
      | 'SN'
      | 'RS'
      | 'SG'
      | 'SK'
      | 'SI'
      | 'ZA'
      | 'KR'
      | 'ES'
      | 'LK'
      | 'SE'
      | 'CH'
      | 'SY'
      | 'TW'
      | 'TZ'
      | 'TH'
      | 'TN'
      | 'TR'
      | 'UG'
      | 'AE'
      | 'GB'
      | 'US'
      | 'UY'
      | 'VE'
      | 'VN'
      | 'YE';
    /**
     * Derived from the country on save.
     */
    region?:
      | ('europe' | 'middle-east' | 'africa' | 'latin-america' | 'north-america' | 'asia' | 'oceania' | 'algeria')
      | null;
    /**
     * Sub-national origin, e.g. "Piedmont", "Kalamata".
     */
    producerRegion?: string | null;
    /**
     * Protected designation, e.g. DOP / PDO / IGP.
     */
    appellation?: string | null;
  };
  /**
   * Brief summary shown on listing cards.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * First image is the primary. Alt text lives on the media item.
   */
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * AED. Cheapest variant — the "from" price. Derived on save.
   */
  basePrice?: number | null;
  /**
   * Compare-at of the cheapest variant.
   */
  baseCompareAt?: number | null;
  /**
   * The orderable unit. Single-size products get exactly one variant. SKUs must be unique across the whole catalogue.
   */
  variants: {
    sku: string;
    /**
     * e.g. "30g", "1kg", "6 × 750ml".
     */
    size: string;
    /**
     * AED.
     */
    price: number;
    /**
     * AED, before sale.
     */
    compareAt?: number | null;
    /**
     * UPC/EAN.
     */
    barcode?: string | null;
    weightGrams?: number | null;
    inStock?: boolean | null;
    /**
     * Preselected on the product page. Exactly one per product.
     */
    isDefault?: boolean | null;
    image?: (number | null) | Media;
    /**
     * Stock per warehouse, for this size.
     */
    inventory?:
      | {
          warehouse: number | Warehouse;
          quantity: number;
          reservedQuantity?: number | null;
          lowStockThreshold?: number | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * True when any variant is in stock. Derived on save.
   */
  inStock?: boolean | null;
  isFeatured?: boolean | null;
  /**
   * Lower sorts first among featured products.
   */
  featuredRank?: number | null;
  /**
   * Sort key for New Arrivals. Stamped on first publish and preserved across re-imports, so a catalogue reload does not make everything new.
   */
  publishedAt?: string | null;
  dietary?: {
    isHalal?: boolean | null;
    isLactoseFree?: boolean | null;
    isOrganic?: boolean | null;
    isVegetarian?: boolean | null;
    isVegan?: boolean | null;
    isGlutenFree?: boolean | null;
  };
  ingredients?: string | null;
  allergens?: string | null;
  nutritionPer100g?: {
    energyKJ?: number | null;
    energyKcal?: number | null;
    protein?: number | null;
    carbohydrates?: number | null;
    sugars?: number | null;
    fat?: number | null;
    saturatedFat?: number | null;
    salt?: number | null;
    fibre?: number | null;
  };
  storageInstructions?: string | null;
  packaging?: string | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  shipping?: {
    dimensionsCm?: {
      length?: number | null;
      width?: number | null;
      height?: number | null;
    };
    shippingClass?: ('standard' | 'express' | 'frozen' | 'fragile' | 'oversized') | null;
    freeShippingEligible?: boolean | null;
    handlingDays?: number | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  source?: {
    /**
     * Importer that owns this row, e.g. "garcia-de-la-cruz".
     */
    provider?: string | null;
    /**
     * Identifier in the source system. The upsert key.
     */
    externalId?: string | null;
    /**
     * Source slug, kept for tracing back by hand.
     */
    handle?: string | null;
    url?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Derived from the title on save.
   */
  slug: string;
  /**
   * Leave empty for a department (top-level category).
   */
  parent?: (number | null) | Category;
  /**
   * Every category above this one. Lets a department listing select all its descendants in one query.
   */
  ancestors?: (number | Category)[] | null;
  /**
   * Slug path, e.g. "caviar-roe/sturgeon-caviar". Used for breadcrumbs.
   */
  path?: string | null;
  /**
   * True when this category has no parent.
   */
  isDepartment?: boolean | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Manual sort order for display.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Where this file was fetched from, when it came from an external catalogue. An importer matches on it so a second run reuses this upload instead of creating a near-duplicate — filenames alone are not enough, two products can both ship a "Garlic-1.jpg".
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  website?: string | null;
  country: string;
  description?: string | null;
  contactPerson?: {
    name?: string | null;
    title?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: number;
  name: string;
  slug: string;
  isActive: boolean;
  address?: {
    line1?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "b2b-inquiries".
 */
export interface B2BInquiry {
  id: number;
  company: string;
  contactName: string;
  email: string;
  phone?: string | null;
  products?: (number | Product)[] | null;
  message: string;
  status: 'new' | 'in_review' | 'quoted' | 'won' | 'lost';
  assignedOffice?: (number | null) | OfficeLocation;
  /**
   * Internal notes (not visible to the customer).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-locations".
 */
export interface OfficeLocation {
  id: number;
  city: string;
  country: string;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * The "Shop by Region" row on the homepage. Products are matched by their country of origin — these rows only control wording, artwork and priority.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  /**
   * Which region this row presents. The list is fixed: a region exists because countries are mapped to it, not because a row was added here.
   */
  slug: 'algeria' | 'europe' | 'middle-east' | 'africa' | 'latin-america' | 'north-america' | 'asia' | 'oceania';
  /**
   * Big name on the card, e.g. "Europe".
   */
  label: string;
  /**
   * Small line above the label.
   */
  eyebrow?: string | null;
  /**
   * Short blurb used on listing pages and in the mega menu.
   */
  description?: string | null;
  /**
   * Card artwork. Without one the bundled default for this region is used.
   */
  image?: (number | null) | Media;
  /**
   * Uncheck to hide the region without deleting it.
   */
  active?: boolean | null;
  /**
   * Draws this region as the spotlight card on the homepage: wider, framed and badged. Meant for one region at a time.
   */
  highlighted?: boolean | null;
  /**
   * Lower shows first. Decimals and negatives are allowed, so a region can be slotted between two others (2.5) or pushed to the front (0) without renumbering the rest. Left blank, it falls behind every region that has a number.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Applications from the /portal/vendor questionnaire. Move one through New → In review → Verification → Approved as the onboarding journey on /vendors describes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-applications".
 */
export interface VendorApplication {
  id: number;
  companyName: string;
  /**
   * If it differs from the registered name.
   */
  tradingName?: string | null;
  /**
   * The five partner types on /vendors, plus the adjacent ones.
   */
  businessType:
    | 'producer'
    | 'cooperative'
    | 'marine'
    | 'processor'
    | 'brand_owner'
    | 'exporter'
    | 'distributor'
    | 'logistics';
  website?: string | null;
  /**
   * Four digits.
   */
  yearEstablished?: number | null;
  registrationNumber?: string | null;
  taxId?: string | null;
  employeeBand?: ('1_10' | '11_50' | '51_200' | '201_1000' | 'over_1000') | null;
  /**
   * Indicative only, and optional to disclose.
   */
  annualTurnover?: ('under_250k' | '250k_1m' | '1m_5m' | '5m_20m' | 'over_20m' | 'undisclosed') | null;
  /**
   * What the business does, how long it has done it, and at what scale.
   */
  companyProfile: string;
  contactName: string;
  contactRole?: string | null;
  email: string;
  phone: string;
  whatsapp?: string | null;
  preferredContact?: ('email' | 'phone' | 'whatsapp') | null;
  country:
    | 'DZ'
    | 'AR'
    | 'AU'
    | 'AT'
    | 'BH'
    | 'BD'
    | 'BE'
    | 'BO'
    | 'BR'
    | 'KH'
    | 'CA'
    | 'CL'
    | 'CN'
    | 'CO'
    | 'CR'
    | 'CI'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'ET'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GH'
    | 'GR'
    | 'GT'
    | 'HN'
    | 'HU'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IL'
    | 'IT'
    | 'JP'
    | 'JO'
    | 'KE'
    | 'KW'
    | 'LB'
    | 'LY'
    | 'MG'
    | 'MY'
    | 'MX'
    | 'MA'
    | 'NP'
    | 'NL'
    | 'NZ'
    | 'NI'
    | 'NG'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PS'
    | 'PA'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PL'
    | 'PT'
    | 'QA'
    | 'RO'
    | 'RW'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ZA'
    | 'KR'
    | 'ES'
    | 'LK'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TZ'
    | 'TH'
    | 'TN'
    | 'TR'
    | 'UG'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UY'
    | 'VE'
    | 'VN'
    | 'YE';
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  /**
   * Where the product is actually made, if not the address above.
   */
  productionSites?: string | null;
  /**
   * Where the range would sit in our catalogue.
   */
  categories?: (number | Category)[] | null;
  /**
   * The range, in the applicant’s own words.
   */
  productSummary: string;
  brandsOwned?: string | null;
  /**
   * e.g. "20 tonnes / month", "40,000 units / month".
   */
  monthlyCapacity?: string | null;
  minimumOrder?: string | null;
  leadTime?: ('under_2w' | '2_4w' | '4_8w' | 'over_8w') | null;
  shelfLifeMonths?: number | null;
  temperatureRegimes?: ('ambient' | 'chilled' | 'frozen' | 'controlled_atmosphere')[] | null;
  packagingFormats?: string | null;
  /**
   * Harvest windows, or months when supply is constrained.
   */
  seasonality?: string | null;
  privateLabelCapable?: boolean | null;
  samplesAvailable?: boolean | null;
  certifications?:
    | (
        | 'haccp'
        | 'iso_22000'
        | 'iso_9001'
        | 'brcgs'
        | 'ifs'
        | 'fssc_22000'
        | 'globalgap'
        | 'halal'
        | 'kosher'
        | 'organic'
        | 'fairtrade'
        | 'rainforest_alliance'
        | 'msc_asc'
        | 'non_gmo'
        | 'sedex'
        | 'other'
      )[]
    | null;
  /**
   * Upload the certificate itself where the applicant has it.
   */
  certificationDocs?:
    | {
        name: string;
        issuingBody?: string | null;
        reference?: string | null;
        expiresAt?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  traceability: 'batch' | 'farm' | 'chain_of_custody' | 'none';
  recallProcedure?: boolean | null;
  lastAuditBody?: string | null;
  lastAuditDate?: string | null;
  /**
   * HACCP plan, testing regime, in-house laboratory, and so on.
   */
  foodSafetyNotes?: string | null;
  /**
   * All three are non-negotiable on /vendors. An application that cannot affirm them is not one we can take forward.
   */
  ethics?: {
    noForcedOrChildLabour?: boolean | null;
    safeWorkingConditions?: boolean | null;
    labourLawCompliance?: boolean | null;
    notes?: string | null;
  };
  insurance?: {
    productLiability?: boolean | null;
    insurer?: string | null;
    coverAmount?: string | null;
  };
  /**
   * Water, waste, energy, packaging recyclability, or certification roadmaps.
   */
  sustainability?: string | null;
  exportsToday?: boolean | null;
  exportMarkets?: string | null;
  gccExperience?: boolean | null;
  uaeRegistered?: boolean | null;
  incoterms?: ('exw' | 'fca' | 'fob' | 'cfr' | 'cif' | 'cpt' | 'cip' | 'dap' | 'ddp')[] | null;
  portsOfLoading?: string | null;
  coldChainCapable?: boolean | null;
  logisticsNotes?: string | null;
  currencies?: ('AED' | 'USD' | 'EUR' | 'GBP' | 'INR')[] | null;
  paymentTerms?: ('advance' | 'letter_of_credit' | 'dp' | 'net_30' | 'net_60' | 'net_90' | 'negotiable')[] | null;
  priceList?: (number | null) | Media;
  catalogue?: (number | null) | Media;
  openToExclusivity?: boolean | null;
  marketingSupport?: string | null;
  /**
   * Existing customers we may contact during verification.
   */
  references?:
    | {
        company: string;
        contactName?: string | null;
        email?: string | null;
        phone?: string | null;
        /**
         * e.g. "Distributor, 3 years".
         */
        relationship?: string | null;
        id?: string | null;
      }[]
    | null;
  howHeard?: ('trade_show' | 'referral' | 'search' | 'social' | 'outreach' | 'other') | null;
  additionalNotes?: string | null;
  signatoryName: string;
  signatoryRole: string;
  declarationAccepted?: boolean | null;
  consentContact?: boolean | null;
  /**
   * Quoted back to the applicant on submission, and what they use to check progress at /portal/vendor/status. Stamped on create.
   */
  reference?: string | null;
  submittedAt?: string | null;
  status: 'new' | 'in_review' | 'verification' | 'approved' | 'on_hold' | 'rejected';
  /**
   * Set on approval. Earned by performance, not agreed at signing.
   */
  tier?: ('developmental' | 'approved' | 'strategic') | null;
  reviewer?: (number | null) | User;
  /**
   * The supplier record created once this application is approved.
   */
  linkedSupplier?: (number | null) | Supplier;
  /**
   * Never shown to the applicant.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chefs registered at /portal/chef. Verifying one is a badge on their recipes; it is not what lets them publish — every recipe is reviewed on its own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chef-profiles".
 */
export interface ChefProfile {
  id: number;
  /**
   * The login this profile belongs to. One profile per account.
   */
  account: number | User;
  displayName: string;
  /**
   * Derived from the display name on save.
   */
  slug: string;
  email: string;
  phone?: string | null;
  portrait?: (number | null) | Media;
  chefRole:
    | 'executive_chef'
    | 'head_chef'
    | 'sous_chef'
    | 'pastry_chef'
    | 'chef_de_partie'
    | 'private_chef'
    | 'consultant'
    | 'instructor'
    | 'developer'
    | 'home_cook';
  establishment?: string | null;
  kitchenType?:
    | (
        | 'fine_dining'
        | 'casual'
        | 'hotel'
        | 'bakery'
        | 'cafe'
        | 'catering'
        | 'cloud_kitchen'
        | 'school'
        | 'private'
        | 'independent'
      )
    | null;
  experience: 'under_2' | '2_5' | '5_10' | '10_20' | 'over_20';
  cuisines: (
    | 'italian'
    | 'french'
    | 'spanish'
    | 'mediterranean'
    | 'middle_eastern'
    | 'levantine'
    | 'north_african'
    | 'indian'
    | 'japanese'
    | 'chinese'
    | 'thai'
    | 'korean'
    | 'latin_american'
    | 'nordic'
    | 'modern_european'
    | 'pastry'
    | 'plant_based'
  )[];
  specialities?: string | null;
  /**
   * Two or three sentences. Runs under the byline on a published recipe.
   */
  bio: string;
  city?: string | null;
  country:
    | 'DZ'
    | 'AR'
    | 'AU'
    | 'AT'
    | 'BH'
    | 'BD'
    | 'BE'
    | 'BO'
    | 'BR'
    | 'KH'
    | 'CA'
    | 'CL'
    | 'CN'
    | 'CO'
    | 'CR'
    | 'CI'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'ET'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GH'
    | 'GR'
    | 'GT'
    | 'HN'
    | 'HU'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IL'
    | 'IT'
    | 'JP'
    | 'JO'
    | 'KE'
    | 'KW'
    | 'LB'
    | 'LY'
    | 'MG'
    | 'MY'
    | 'MX'
    | 'MA'
    | 'NP'
    | 'NL'
    | 'NZ'
    | 'NI'
    | 'NG'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PS'
    | 'PA'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PL'
    | 'PT'
    | 'QA'
    | 'RO'
    | 'RW'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ZA'
    | 'KR'
    | 'ES'
    | 'LK'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TZ'
    | 'TH'
    | 'TN'
    | 'TR'
    | 'UG'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UY'
    | 'VE'
    | 'VN'
    | 'YE';
  links?: {
    website?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
  };
  awards?: string | null;
  qualifications?:
    | {
        name: string;
        institution?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Helps us suggest a first recipe brief.
   */
  familiarProducts?: (number | Product)[] | null;
  motivation?: string | null;
  consentPublish?: boolean | null;
  consentTerms?: boolean | null;
  status: 'pending' | 'verified' | 'on_hold' | 'declined';
  /**
   * Surfaces the chef on /recipes.
   */
  featured?: boolean | null;
  /**
   * Never shown to the chef.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            style?: ('fullscreen' | 'split' | 'contained') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            products?: (number | Product)[] | null;
            layout?: ('grid' | 'carousel') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            heading?: string | null;
            categories?: (number | Category)[] | null;
            style?: ('horizontal-scroll' | 'grid') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryShowcase';
          }
        | {
            heading?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            style?: ('carousel' | 'grid') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right' | 'fullbleed') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'experience';
          }
        | {
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'story';
          }
        | {
            heading?: string | null;
            offices?: (number | OfficeLocation)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'officeLocations';
          }
        | {
            heading: string;
            subheading?: string | null;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  logo: number | Media;
                  name: string;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersLogo';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('prose' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  company?: string | null;
  quote: string;
  image?: (number | null) | Media;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary shown on listing cards.
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories?: (number | BlogCategory)[] | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submitted from /portal/chef. A recipe is only visible on the storefront once its status is Published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  title: string;
  /**
   * Derived from the title on save.
   */
  slug: string;
  /**
   * One or two sentences. Used on the recipe card and in search results.
   */
  summary: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  course:
    | 'starter'
    | 'soup'
    | 'salad'
    | 'main'
    | 'side'
    | 'pasta_rice'
    | 'bakery'
    | 'dessert'
    | 'sauce'
    | 'breakfast'
    | 'drink';
  cuisine?:
    | (
        | 'italian'
        | 'french'
        | 'spanish'
        | 'mediterranean'
        | 'middle_eastern'
        | 'levantine'
        | 'north_african'
        | 'indian'
        | 'japanese'
        | 'chinese'
        | 'thai'
        | 'korean'
        | 'latin_american'
        | 'nordic'
        | 'modern_european'
        | 'pastry'
        | 'plant_based'
      )
    | null;
  difficulty?: ('easy' | 'intermediate' | 'advanced') | null;
  /**
   * What the quantities below make. The portion scaler works off this.
   */
  servings: number;
  prepMinutes?: number | null;
  cookMinutes?: number | null;
  /**
   * Preparation plus cooking. Derived on save.
   */
  totalMinutes?: number | null;
  /**
   * Every ingredient is a product from our catalogue, with a quantity and a unit. There is no free-text line by design.
   */
  ingredients: {
    product: number | Product;
    /**
     * Optional. The exact variant used, when the size matters to the result.
     */
    variantSku?: string | null;
    quantity?: number | null;
    unit:
      | 'g'
      | 'kg'
      | 'mg'
      | 'oz'
      | 'lb'
      | 'ml'
      | 'cl'
      | 'l'
      | 'tsp'
      | 'tbsp'
      | 'cup'
      | 'fl-oz'
      | 'piece'
      | 'clove'
      | 'slice'
      | 'sheet'
      | 'sprig'
      | 'leaf'
      | 'bunch'
      | 'handful'
      | 'pinch'
      | 'dash'
      | 'drop'
      | 'can'
      | 'jar'
      | 'packet'
      | 'to-taste';
    /**
     * e.g. "finely chopped", "at room temperature".
     */
    preparation?: string | null;
    /**
     * Groups the line under a heading, e.g. "For the sauce".
     */
    section?: string | null;
    optional?: boolean | null;
    id?: string | null;
  }[];
  method: {
    instruction: string;
    image?: (number | null) | Media;
    /**
     * Shows a timer beside the step.
     */
    timerMinutes?: number | null;
    id?: string | null;
  }[];
  chefTips?: string | null;
  pairing?: string | null;
  /**
   * Anything present beyond what the products themselves declare.
   */
  allergens?: string | null;
  /**
   * The account that wrote it. Pinned from the session — this is what scopes a chef to their own work.
   */
  author: number | User;
  /**
   * The profile behind the byline. Resolved from the author on save.
   */
  chef?: (number | null) | ChefProfile;
  /**
   * Byline, snapshotted at save. Kept here so a public recipe page never has to read the private chef profile.
   */
  chefName?: string | null;
  /**
   * Role and kitchen, snapshotted alongside the name.
   */
  chefTitle?: string | null;
  /**
   * A chef may only choose Draft or Submitted; the rest is an editorial decision.
   */
  status: 'draft' | 'submitted' | 'published' | 'changes_requested' | 'archived';
  /**
   * Shown to the chef in their portal. Say what needs changing.
   */
  reviewFeedback?: string | null;
  /**
   * Never shown to the chef.
   */
  internalNotes?: string | null;
  featured?: boolean | null;
  submittedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Promotional banners shown between the homepage sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * Internal name shown in the admin list.
   */
  title: string;
  /**
   * Which homepage slot this banner appears in.
   */
  placement: 'below-hero' | 'after-best-sellers' | 'after-new-arrivals' | 'before-newsletter';
  variant: 'wide' | 'split' | 'strip';
  /**
   * Used for the text colour and the imageless background.
   */
  theme: 'dark' | 'light' | 'forest';
  /**
   * Small label above the heading, e.g. "New this season".
   */
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  /**
   * Optional. Without one the banner uses a solid brand background.
   */
  image?: (number | null) | Media;
  /**
   * Optional. Shows this product’s photo, name and price beside the text. Ignored on the strip variant. With no link below, the banner links to the product.
   */
  product?: (number | null) | Product;
  /**
   * e.g. "Shop now".
   */
  ctaLabel?: string | null;
  /**
   * e.g. /products?dietary=halal. Left blank, it falls back to the featured product, then to /products.
   */
  ctaHref?: string | null;
  /**
   * Uncheck to hide without deleting.
   */
  active?: boolean | null;
  /**
   * Order within the slot. Lower shows first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Where the subscription originated, e.g. "footer", "popup".
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The "Our people" section on the About page. Leave a row's name blank to advertise it as an open role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * Job title, e.g. "Head of Sourcing". Shown under the name.
   */
  role: string;
  /**
   * Leave blank for a vacancy — the card then reads "Open role" and keeps the job title.
   */
  name?: string | null;
  /**
   * Square portrait, 800 × 800 or larger. Without one the card shows a placeholder.
   */
  photo?: (number | null) | Media;
  /**
   * Renders this person as the wide card beside the grid, with their quote. Check it on one row only — if several are checked the first by priority wins.
   */
  isFounder?: boolean | null;
  /**
   * Only used by the founder card. Quotation marks are added by the page — do not type them.
   */
  quote?: string | null;
  /**
   * Uncheck to hide someone without deleting the row.
   */
  active?: boolean | null;
  /**
   * Lower shows first. Decimals and negatives are allowed, so someone can be slotted between two others (2.5) without renumbering the rest. Left blank, they fall behind everyone who has a number.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'b2b-inquiries';
        value: number | B2BInquiry;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: number | Warehouse;
      } | null)
    | ({
        relationTo: 'vendor-applications';
        value: number | VendorApplication;
      } | null)
    | ({
        relationTo: 'chef-profiles';
        value: number | ChefProfile;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'office-locations';
        value: number | OfficeLocation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  paymentStatus?: T;
  type?: T;
  currency?: T;
  notes?: T;
  internalNotes?: T;
  fulfillment?:
    | T
    | {
        carrier?: T;
        trackingNumber?: T;
        shippedAt?: T;
        deliveredAt?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  timeline?:
    | T
    | {
        event?: T;
        note?: T;
        at?: T;
        by?: T;
        id?: T;
      };
  orderNumber?: T;
  user?: T;
  guestEmail?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        titleSnapshot?: T;
        sizeSnapshot?: T;
        quantity?: T;
        unitAmount?: T;
        currency?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        subtotal?: T;
        shipping?: T;
        tax?: T;
        total?: T;
      };
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "b2b-inquiries_select".
 */
export interface B2BInquiriesSelect<T extends boolean = true> {
  company?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  products?: T;
  message?: T;
  status?: T;
  assignedOffice?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  category?: T;
  brand?: T;
  supplier?: T;
  origin?:
    | T
    | {
        country?: T;
        region?: T;
        producerRegion?: T;
        appellation?: T;
      };
  shortDescription?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  basePrice?: T;
  baseCompareAt?: T;
  variants?:
    | T
    | {
        sku?: T;
        size?: T;
        price?: T;
        compareAt?: T;
        barcode?: T;
        weightGrams?: T;
        inStock?: T;
        isDefault?: T;
        image?: T;
        inventory?:
          | T
          | {
              warehouse?: T;
              quantity?: T;
              reservedQuantity?: T;
              lowStockThreshold?: T;
              id?: T;
            };
        id?: T;
      };
  inStock?: T;
  isFeatured?: T;
  featuredRank?: T;
  publishedAt?: T;
  dietary?:
    | T
    | {
        isHalal?: T;
        isLactoseFree?: T;
        isOrganic?: T;
        isVegetarian?: T;
        isVegan?: T;
        isGlutenFree?: T;
      };
  ingredients?: T;
  allergens?: T;
  nutritionPer100g?:
    | T
    | {
        energyKJ?: T;
        energyKcal?: T;
        protein?: T;
        carbohydrates?: T;
        sugars?: T;
        fat?: T;
        saturatedFat?: T;
        salt?: T;
        fibre?: T;
      };
  storageInstructions?: T;
  packaging?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  shipping?:
    | T
    | {
        dimensionsCm?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
        shippingClass?: T;
        freeShippingEligible?: T;
        handlingDays?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  source?:
    | T
    | {
        provider?: T;
        externalId?: T;
        handle?: T;
        url?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  ancestors?: T;
  path?: T;
  isDepartment?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  logo?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  eyebrow?: T;
  description?: T;
  image?: T;
  active?: T;
  highlighted?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  country?: T;
  description?: T;
  contactPerson?:
    | T
    | {
        name?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  address?:
    | T
    | {
        line1?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-applications_select".
 */
export interface VendorApplicationsSelect<T extends boolean = true> {
  companyName?: T;
  tradingName?: T;
  businessType?: T;
  website?: T;
  yearEstablished?: T;
  registrationNumber?: T;
  taxId?: T;
  employeeBand?: T;
  annualTurnover?: T;
  companyProfile?: T;
  contactName?: T;
  contactRole?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  preferredContact?: T;
  country?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  productionSites?: T;
  categories?: T;
  productSummary?: T;
  brandsOwned?: T;
  monthlyCapacity?: T;
  minimumOrder?: T;
  leadTime?: T;
  shelfLifeMonths?: T;
  temperatureRegimes?: T;
  packagingFormats?: T;
  seasonality?: T;
  privateLabelCapable?: T;
  samplesAvailable?: T;
  certifications?: T;
  certificationDocs?:
    | T
    | {
        name?: T;
        issuingBody?: T;
        reference?: T;
        expiresAt?: T;
        file?: T;
        id?: T;
      };
  traceability?: T;
  recallProcedure?: T;
  lastAuditBody?: T;
  lastAuditDate?: T;
  foodSafetyNotes?: T;
  ethics?:
    | T
    | {
        noForcedOrChildLabour?: T;
        safeWorkingConditions?: T;
        labourLawCompliance?: T;
        notes?: T;
      };
  insurance?:
    | T
    | {
        productLiability?: T;
        insurer?: T;
        coverAmount?: T;
      };
  sustainability?: T;
  exportsToday?: T;
  exportMarkets?: T;
  gccExperience?: T;
  uaeRegistered?: T;
  incoterms?: T;
  portsOfLoading?: T;
  coldChainCapable?: T;
  logisticsNotes?: T;
  currencies?: T;
  paymentTerms?: T;
  priceList?: T;
  catalogue?: T;
  openToExclusivity?: T;
  marketingSupport?: T;
  references?:
    | T
    | {
        company?: T;
        contactName?: T;
        email?: T;
        phone?: T;
        relationship?: T;
        id?: T;
      };
  howHeard?: T;
  additionalNotes?: T;
  signatoryName?: T;
  signatoryRole?: T;
  declarationAccepted?: T;
  consentContact?: T;
  reference?: T;
  submittedAt?: T;
  status?: T;
  tier?: T;
  reviewer?: T;
  linkedSupplier?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chef-profiles_select".
 */
export interface ChefProfilesSelect<T extends boolean = true> {
  account?: T;
  displayName?: T;
  slug?: T;
  email?: T;
  phone?: T;
  portrait?: T;
  chefRole?: T;
  establishment?: T;
  kitchenType?: T;
  experience?: T;
  cuisines?: T;
  specialities?: T;
  bio?: T;
  city?: T;
  country?: T;
  links?:
    | T
    | {
        website?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
      };
  awards?: T;
  qualifications?:
    | T
    | {
        name?: T;
        institution?: T;
        year?: T;
        id?: T;
      };
  familiarProducts?: T;
  motivation?: T;
  consentPublish?: T;
  consentTerms?: T;
  status?: T;
  featured?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              ctaLabel?: T;
              ctaHref?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              heading?: T;
              subheading?: T;
              products?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        categoryShowcase?:
          | T
          | {
              heading?: T;
              categories?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        experience?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        officeLocations?:
          | T
          | {
              heading?: T;
              offices?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              heading?: T;
              subheading?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
        partnersLogo?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  categories?: T;
  author?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  course?: T;
  cuisine?: T;
  difficulty?: T;
  servings?: T;
  prepMinutes?: T;
  cookMinutes?: T;
  totalMinutes?: T;
  ingredients?:
    | T
    | {
        product?: T;
        variantSku?: T;
        quantity?: T;
        unit?: T;
        preparation?: T;
        section?: T;
        optional?: T;
        id?: T;
      };
  method?:
    | T
    | {
        instruction?: T;
        image?: T;
        timerMinutes?: T;
        id?: T;
      };
  chefTips?: T;
  pairing?: T;
  allergens?: T;
  author?: T;
  chef?: T;
  chefName?: T;
  chefTitle?: T;
  status?: T;
  reviewFeedback?: T;
  internalNotes?: T;
  featured?: T;
  submittedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  image?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  placement?: T;
  variant?: T;
  theme?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  image?: T;
  product?: T;
  ctaLabel?: T;
  ctaHref?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  roles?: T;
  addresses?:
    | T
    | {
        label?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  preferredCurrency?: T;
  preferredLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  photo?: T;
  isFounder?: T;
  quote?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-locations_select".
 */
export interface OfficeLocationsSelect<T extends boolean = true> {
  city?: T;
  country?: T;
  address?: T;
  phone?: T;
  email?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  announcementBar?: {
    enabled?: boolean | null;
    message?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
    backgroundColor?: ('gold' | 'forest' | 'obsidian') | null;
  };
  socials?: {
    instagram?: string | null;
    facebook?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
  };
  /**
   * Where staff notifications are sent when an order is paid or an enquiry arrives.
   */
  notifications?: {
    /**
     * Leave blank to fall back to the ADMIN_NOTIFICATION_EMAIL environment variable, then to the published company mailbox.
     */
    orderEmail?: string | null;
    /**
     * Unticking this stops staff alerts only. Customers still receive their own order confirmations.
     */
    enabled?: boolean | null;
  };
  defaultMeta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        href?: string | null;
        type?: ('link' | 'mega-menu') | null;
        megaMenuColumns?:
          | {
              heading?: string | null;
              links?:
                | {
                    label: string;
                    href: string;
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  announcementBar?:
    | T
    | {
        enabled?: T;
        message?: T;
        linkLabel?: T;
        linkHref?: T;
        backgroundColor?: T;
      };
  socials?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        twitter?: T;
        linkedin?: T;
      };
  notifications?:
    | T
    | {
        orderEmail?: T;
        enabled?: T;
      };
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
        megaMenuColumns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}